version: '3'

services:
  loan-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=loandb
  credit-score-service:
    image: di-course/credit-score-service
    ports:
      - 3000:3000